name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install other dependencies
      run: |
        sudo apt install libavahi-compat-libdnssd-dev

    - name: npm install and test
      run: |
        npm ci
        npm run check
      env:
        CI: true
